# Generated by Django 4.2.7 on 2023-11-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_shop_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Shop',
            new_name='name',
        ),
    ]
